apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fintech-app
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: matiasamil833/fintech-frontend:v2
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: frontend
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"