apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: fintech-db
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02ef14a47ecd67a3f # <-- Replace with your EFS File System ID