apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: fintech-db
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi